version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - n 12.18.0
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
