/**
 * FormDesk Backend API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body1 model module.
* @module model/Body1
* @version 1.0.0
*/
export default class Body1 {
    /**
    * Constructs a new <code>Body1</code>.
    * @alias module:model/Body1
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Body1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body1} obj Optional instance to populate.
    * @return {module:model/Body1} The populated <code>Body1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body1();
                        
            
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
            if (data.hasOwnProperty('cc')) {
                obj['cc'] = ApiClient.convertToType(data['cc'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} subject
    */
    subject = undefined;
    /**
    * @member {String} body
    */
    body = undefined;
    /**
    * @member {String} to
    */
    to = undefined;
    /**
    * @member {String} cc
    */
    cc = undefined;




}
