/**
 * FormDesk Backend API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The LoginResponseBody model module.
* @module model/LoginResponseBody
* @version 1.0.0
*/
export default class LoginResponseBody {
    /**
    * Constructs a new <code>LoginResponseBody</code>.
    * @alias module:model/LoginResponseBody
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>LoginResponseBody</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LoginResponseBody} obj Optional instance to populate.
    * @return {module:model/LoginResponseBody} The populated <code>LoginResponseBody</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginResponseBody();
                        
            
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('loginType')) {
                obj['loginType'] = ApiClient.convertToType(data['loginType'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
            if (data.hasOwnProperty('emailid')) {
                obj['emailid'] = ApiClient.convertToType(data['emailid'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('organizationName')) {
                obj['organizationName'] = ApiClient.convertToType(data['organizationName'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} token
    */
    token = undefined;
    /**
    * @member {String} loginType
    */
    loginType = undefined;
    /**
    * @member {String} data
    */
    data = undefined;
    /**
    * @member {String} emailid
    */
    emailid = undefined;
    /**
    * @member {String} role
    */
    role = undefined;
    /**
    * @member {String} organizationName
    */
    organizationName = undefined;




}
