/**
 * FormDesk Backend API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The LoginRequestBody model module.
* @module model/LoginRequestBody
* @version 1.0.0
*/
export default class LoginRequestBody {
    /**
    * Constructs a new <code>LoginRequestBody</code>.
    * @alias module:model/LoginRequestBody
    * @class
    * @param email {String} 
    * @param password {String} 
    */

    constructor(email, password) {
        
        
        this['email'] = email;
        this['password'] = password;
        
    }

    /**
    * Constructs a <code>LoginRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LoginRequestBody} obj Optional instance to populate.
    * @return {module:model/LoginRequestBody} The populated <code>LoginRequestBody</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginRequestBody();
                        
            
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} email
    */
    email = undefined;
    /**
    * @member {String} password
    */
    password = undefined;




}
