/**
 * FormDesk Backend API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Users model module.
* @module model/Users
* @version 1.0.0
*/
export default class Users {
    /**
    * Constructs a new <code>Users</code>.
    * @alias module:model/Users
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Users</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Users} obj Optional instance to populate.
    * @return {module:model/Users} The populated <code>Users</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Users();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('organizationID')) {
                obj['organizationID'] = ApiClient.convertToType(data['organizationID'], 'String');
            }
            if (data.hasOwnProperty('userdetails')) {
                obj['userdetails'] = ApiClient.convertToType(data['userdetails'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} email
    */
    email = undefined;
    /**
    * @member {String} password
    */
    password = undefined;
    /**
    * @member {String} role
    */
    role = undefined;
    /**
    * @member {String} organizationID
    */
    organizationID = undefined;
    /**
    * @member {String} userdetails
    */
    userdetails = undefined;




}
