/**
 * FormDesk Backend API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Usersid model module.
* @module model/Usersid
* @version 1.0.0
*/
export default class Usersid {
    /**
    * Constructs a new <code>Usersid</code>.
    * @alias module:model/Usersid
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Usersid</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Usersid} obj Optional instance to populate.
    * @return {module:model/Usersid} The populated <code>Usersid</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Usersid();
                        
            
            if (data.hasOwnProperty('userid')) {
                obj['userid'] = ApiClient.convertToType(data['userid'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('organizationID')) {
                obj['organizationID'] = ApiClient.convertToType(data['organizationID'], 'String');
            }
            if (data.hasOwnProperty('userdetails')) {
                obj['userdetails'] = ApiClient.convertToType(data['userdetails'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} userid
    */
    userid = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} email
    */
    email = undefined;
    /**
    * @member {String} role
    */
    role = undefined;
    /**
    * @member {String} organizationID
    */
    organizationID = undefined;
    /**
    * @member {String} userdetails
    */
    userdetails = undefined;




}
